-- Signa initial schema (Cloudflare D1 / SQLite).
-- Conventions:
--   * IDs are opaque prefixed random strings generated by the application.
--   * Timestamps are integer milliseconds since the Unix epoch (UTC).
--   * No table stores translation source text except the ephemeral
--     translation_job_inputs table, which is purged after processing/expiry.
--   * Secrets (passwords, session tokens, one-time tokens) are stored only as hashes.

PRAGMA foreign_keys = ON;

-- ---------------------------------------------------------------------------
-- Identity
-- ---------------------------------------------------------------------------
CREATE TABLE users (
  id                 TEXT PRIMARY KEY,
  email              TEXT NOT NULL,
  email_normalized   TEXT NOT NULL UNIQUE,
  email_verified_at  INTEGER,
  name               TEXT NOT NULL,
  status             TEXT NOT NULL DEFAULT 'active'
                     CHECK (status IN ('active', 'suspended', 'deactivated', 'deleted')),
  platform_role      TEXT NOT NULL DEFAULT 'user'
                     CHECK (platform_role IN ('user', 'support', 'admin', 'superadmin')),
  locale             TEXT NOT NULL DEFAULT 'he' CHECK (locale IN ('he', 'en')),
  direction          TEXT CHECK (direction IN ('ltr', 'rtl')), -- NULL = derived from locale
  time_zone          TEXT NOT NULL DEFAULT 'Asia/Jerusalem',
  accessibility_json TEXT NOT NULL DEFAULT '{}', -- reduceMotion, highContrast, largeText, captions
  preferences_json   TEXT NOT NULL DEFAULT '{}', -- defaultMode, playbackSpeed
  -- Saved history is OFF by default. It is enabled only by an explicit user action,
  -- and the consent timestamp + disclosure version are recorded.
  history_enabled    INTEGER NOT NULL DEFAULT 0,
  history_consent_at INTEGER,
  history_consent_version TEXT,
  created_at         INTEGER NOT NULL,
  updated_at         INTEGER NOT NULL,
  deleted_at         INTEGER
);
CREATE INDEX idx_users_status ON users (status);
CREATE INDEX idx_users_created_at ON users (created_at);

CREATE TABLE user_credentials (
  user_id             TEXT PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
  password_hash       TEXT NOT NULL,
  password_updated_at INTEGER NOT NULL
);

-- External identities (e.g. Google OAuth). Only the provider subject is stored.
CREATE TABLE auth_identities (
  id               TEXT PRIMARY KEY,
  user_id          TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  provider         TEXT NOT NULL,
  provider_subject TEXT NOT NULL,
  created_at       INTEGER NOT NULL,
  UNIQUE (provider, provider_subject)
);
CREATE INDEX idx_auth_identities_user ON auth_identities (user_id);

CREATE TABLE sessions (
  id                TEXT PRIMARY KEY,
  user_id           TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  token_hash        TEXT NOT NULL UNIQUE,
  auth_method       TEXT NOT NULL DEFAULT 'password',
  user_agent        TEXT, -- truncated, informational only
  created_at        INTEGER NOT NULL,
  last_seen_at      INTEGER NOT NULL,
  authenticated_at  INTEGER NOT NULL, -- last time the user proved credentials (step-up auth)
  expires_at        INTEGER NOT NULL,
  revoked_at        INTEGER,
  revoked_reason    TEXT
);
CREATE INDEX idx_sessions_user ON sessions (user_id, revoked_at);
CREATE INDEX idx_sessions_expires ON sessions (expires_at);

CREATE TABLE one_time_tokens (
  id          TEXT PRIMARY KEY,
  user_id     TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  purpose     TEXT NOT NULL CHECK (purpose IN ('email_verification', 'password_reset')),
  token_hash  TEXT NOT NULL UNIQUE,
  created_at  INTEGER NOT NULL,
  expires_at  INTEGER NOT NULL,
  used_at     INTEGER
);
CREATE INDEX idx_one_time_tokens_user ON one_time_tokens (user_id, purpose);

-- OAuth state (PKCE verifier) — short lived.
CREATE TABLE oauth_states (
  state_hash    TEXT PRIMARY KEY,
  provider      TEXT NOT NULL,
  code_verifier TEXT NOT NULL,
  redirect_path TEXT NOT NULL,
  created_at    INTEGER NOT NULL,
  expires_at    INTEGER NOT NULL
);

-- Fixed-window rate limiting. Keys contain only keyed hashes of identifiers.
CREATE TABLE rate_limits (
  key          TEXT NOT NULL,
  window_start INTEGER NOT NULL,
  count        INTEGER NOT NULL,
  expires_at   INTEGER NOT NULL,
  PRIMARY KEY (key, window_start)
);
CREATE INDEX idx_rate_limits_expires ON rate_limits (expires_at);

-- ---------------------------------------------------------------------------
-- Organizations
-- ---------------------------------------------------------------------------
CREATE TABLE organizations (
  id               TEXT PRIMARY KEY,
  name             TEXT NOT NULL,
  slug             TEXT NOT NULL UNIQUE,
  status           TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'suspended', 'deleted')),
  default_locale   TEXT NOT NULL DEFAULT 'he' CHECK (default_locale IN ('he', 'en')),
  settings_json    TEXT NOT NULL DEFAULT '{}',
  created_by       TEXT REFERENCES users (id) ON DELETE SET NULL,
  suspended_at     INTEGER,
  suspended_reason TEXT,
  created_at       INTEGER NOT NULL,
  updated_at       INTEGER NOT NULL
);

CREATE TABLE organization_members (
  organization_id TEXT NOT NULL REFERENCES organizations (id) ON DELETE CASCADE,
  user_id         TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  role            TEXT NOT NULL CHECK (role IN ('owner', 'admin', 'member')),
  created_at      INTEGER NOT NULL,
  updated_at      INTEGER NOT NULL,
  PRIMARY KEY (organization_id, user_id)
);
CREATE INDEX idx_org_members_user ON organization_members (user_id);

CREATE TABLE organization_invitations (
  id               TEXT PRIMARY KEY,
  organization_id  TEXT NOT NULL REFERENCES organizations (id) ON DELETE CASCADE,
  email_normalized TEXT NOT NULL,
  role             TEXT NOT NULL CHECK (role IN ('admin', 'member')),
  token_hash       TEXT NOT NULL UNIQUE,
  invited_by       TEXT REFERENCES users (id) ON DELETE SET NULL,
  created_at       INTEGER NOT NULL,
  expires_at       INTEGER NOT NULL,
  accepted_at      INTEGER,
  accepted_by      TEXT REFERENCES users (id) ON DELETE SET NULL,
  revoked_at       INTEGER
);
CREATE INDEX idx_org_invitations_org ON organization_invitations (organization_id);

-- ---------------------------------------------------------------------------
-- Plans, entitlements, subscriptions, billing
-- ---------------------------------------------------------------------------
CREATE TABLE plans (
  id                TEXT PRIMARY KEY, -- 'free' | 'pro' | 'business' | future plans
  name_en           TEXT NOT NULL,
  name_he           TEXT NOT NULL,
  is_active         INTEGER NOT NULL DEFAULT 1,
  is_public         INTEGER NOT NULL DEFAULT 1,
  -- How the plan can be obtained: self-service checkout, waitlist, or sales contact.
  availability      TEXT NOT NULL DEFAULT 'available'
                    CHECK (availability IN ('available', 'waitlist', 'contact_sales')),
  sort_order        INTEGER NOT NULL DEFAULT 0,
  -- Commercial pricing is intentionally NULL until configured by an operator.
  pricing_json      TEXT,
  trial_days        INTEGER NOT NULL DEFAULT 0,
  grace_period_days INTEGER NOT NULL DEFAULT 0,
  created_at        INTEGER NOT NULL,
  updated_at        INTEGER NOT NULL
);

CREATE TABLE plan_waitlist (
  plan_id    TEXT NOT NULL REFERENCES plans (id) ON DELETE CASCADE,
  user_id    TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  created_at INTEGER NOT NULL,
  PRIMARY KEY (plan_id, user_id)
);

CREATE TABLE plan_entitlements (
  plan_id    TEXT NOT NULL REFERENCES plans (id) ON DELETE CASCADE,
  key        TEXT NOT NULL,
  value_json TEXT NOT NULL,
  updated_at INTEGER NOT NULL,
  PRIMARY KEY (plan_id, key)
);

CREATE TABLE subscriptions (
  id                        TEXT PRIMARY KEY,
  subject_type              TEXT NOT NULL CHECK (subject_type IN ('user', 'organization')),
  subject_id                TEXT NOT NULL,
  plan_id                   TEXT NOT NULL REFERENCES plans (id),
  status                    TEXT NOT NULL
                            CHECK (status IN ('trialing', 'active', 'past_due', 'cancelled', 'expired', 'suspended')),
  provider                  TEXT NOT NULL,
  provider_customer_ref     TEXT,
  provider_subscription_ref TEXT,
  trial_ends_at             INTEGER,
  current_period_start      INTEGER,
  current_period_end        INTEGER,
  cancel_at_period_end      INTEGER NOT NULL DEFAULT 0,
  cancelled_at              INTEGER,
  grace_until               INTEGER,
  created_at                INTEGER NOT NULL,
  updated_at                INTEGER NOT NULL
);
-- At most one live subscription per billing subject.
CREATE UNIQUE INDEX uq_subscriptions_live_subject ON subscriptions (subject_type, subject_id)
  WHERE status IN ('trialing', 'active', 'past_due', 'suspended');
CREATE UNIQUE INDEX uq_subscriptions_provider_ref ON subscriptions (provider, provider_subscription_ref)
  WHERE provider_subscription_ref IS NOT NULL;

CREATE TABLE subscription_history (
  id              TEXT PRIMARY KEY,
  subscription_id TEXT NOT NULL REFERENCES subscriptions (id) ON DELETE CASCADE,
  from_status     TEXT,
  to_status       TEXT NOT NULL,
  from_plan_id    TEXT,
  to_plan_id      TEXT NOT NULL,
  reason          TEXT NOT NULL,
  actor_type      TEXT NOT NULL CHECK (actor_type IN ('system', 'user', 'admin', 'provider')),
  actor_id        TEXT,
  created_at      INTEGER NOT NULL
);
CREATE INDEX idx_subscription_history_sub ON subscription_history (subscription_id, created_at);

CREATE TABLE checkout_sessions (
  id                   TEXT PRIMARY KEY,
  provider             TEXT NOT NULL,
  provider_session_ref TEXT NOT NULL,
  subject_type         TEXT NOT NULL CHECK (subject_type IN ('user', 'organization')),
  subject_id           TEXT NOT NULL,
  plan_id              TEXT NOT NULL REFERENCES plans (id),
  created_by           TEXT REFERENCES users (id) ON DELETE SET NULL,
  status               TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'completed', 'expired')),
  created_at           INTEGER NOT NULL,
  expires_at           INTEGER NOT NULL,
  UNIQUE (provider, provider_session_ref)
);

-- Webhook events: only identifiers and processing state, never raw payment data.
CREATE TABLE payment_webhook_events (
  id                TEXT PRIMARY KEY,
  provider          TEXT NOT NULL,
  provider_event_id TEXT NOT NULL,
  event_type        TEXT NOT NULL,
  status            TEXT NOT NULL CHECK (status IN ('processing', 'processed', 'ignored', 'failed')),
  error_code        TEXT,
  received_at       INTEGER NOT NULL,
  processed_at      INTEGER,
  UNIQUE (provider, provider_event_id)
);

-- ---------------------------------------------------------------------------
-- Usage metering (aggregate counters, no content)
-- ---------------------------------------------------------------------------
CREATE TABLE usage_counters (
  subject_type TEXT NOT NULL CHECK (subject_type IN ('user', 'organization')),
  subject_id   TEXT NOT NULL,
  feature      TEXT NOT NULL,
  period       TEXT NOT NULL, -- 'YYYY-MM' (UTC)
  count        INTEGER NOT NULL DEFAULT 0 CHECK (count >= 0),
  updated_at   INTEGER NOT NULL,
  PRIMARY KEY (subject_type, subject_id, feature, period)
);

CREATE TABLE usage_events (
  id              TEXT PRIMARY KEY,
  request_id      TEXT NOT NULL,
  idempotency_key TEXT,
  request_fingerprint TEXT, -- keyed HMAC of the request (detects key reuse with different input)
  user_id         TEXT NOT NULL,
  organization_id TEXT,
  subject_type    TEXT NOT NULL,
  subject_id      TEXT NOT NULL,
  feature         TEXT NOT NULL,
  period          TEXT NOT NULL,
  units           INTEGER NOT NULL DEFAULT 1,
  outcome         TEXT NOT NULL CHECK (outcome IN ('reserved', 'succeeded', 'failed', 'rejected')),
  retry_count     INTEGER NOT NULL DEFAULT 0,
  error_code      TEXT,
  created_at      INTEGER NOT NULL,
  updated_at      INTEGER NOT NULL
);
CREATE UNIQUE INDEX uq_usage_events_idem ON usage_events (user_id, feature, idempotency_key)
  WHERE idempotency_key IS NOT NULL;
CREATE INDEX idx_usage_events_subject ON usage_events (subject_type, subject_id, period);
CREATE INDEX idx_usage_events_created ON usage_events (created_at);

-- ---------------------------------------------------------------------------
-- Sign translation jobs (metadata only; inputs/results are ephemeral tables)
-- ---------------------------------------------------------------------------
CREATE TABLE translation_jobs (
  id                  TEXT PRIMARY KEY,
  user_id             TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  organization_id     TEXT REFERENCES organizations (id) ON DELETE CASCADE,
  kind                TEXT NOT NULL DEFAULT 'sign',
  status              TEXT NOT NULL
                      CHECK (status IN ('queued', 'processing', 'completed', 'partially_completed',
                                        'failed', 'cancelled', 'expired')),
  idempotency_key     TEXT,
  request_fingerprint TEXT NOT NULL, -- keyed HMAC of the request, never the text itself
  language            TEXT NOT NULL,
  output_format       TEXT NOT NULL,
  provider            TEXT,
  verification_status TEXT,
  attempts            INTEGER NOT NULL DEFAULT 0,
  max_attempts        INTEGER NOT NULL,
  failure_code        TEXT,
  usage_event_id      TEXT,
  lease_until         INTEGER,
  created_at          INTEGER NOT NULL,
  updated_at          INTEGER NOT NULL,
  started_at          INTEGER,
  completed_at        INTEGER,
  deadline_at         INTEGER NOT NULL,
  expires_at          INTEGER NOT NULL
);
CREATE UNIQUE INDEX uq_translation_jobs_idem ON translation_jobs (user_id, idempotency_key)
  WHERE idempotency_key IS NOT NULL;
CREATE INDEX idx_translation_jobs_user_status ON translation_jobs (user_id, status);
CREATE INDEX idx_translation_jobs_org_status ON translation_jobs (organization_id, status);
CREATE INDEX idx_translation_jobs_status_deadline ON translation_jobs (status, deadline_at);

-- EPHEMERAL: source text, deleted once the job reaches a terminal state or expires.
CREATE TABLE translation_job_inputs (
  job_id      TEXT PRIMARY KEY REFERENCES translation_jobs (id) ON DELETE CASCADE,
  source_text TEXT NOT NULL,
  expires_at  INTEGER NOT NULL
);

-- EPHEMERAL: normalized result, deleted after the result retention window.
CREATE TABLE translation_job_results (
  job_id      TEXT PRIMARY KEY REFERENCES translation_jobs (id) ON DELETE CASCADE,
  result_json TEXT NOT NULL,
  expires_at  INTEGER NOT NULL
);

-- ---------------------------------------------------------------------------
-- Sign dictionary & animation asset registry
-- ---------------------------------------------------------------------------
CREATE TABLE sign_entries (
  id                 TEXT PRIMARY KEY,
  sign_code          TEXT NOT NULL UNIQUE,  -- human-readable, e.g. "SG-0001"
  canonical_label    TEXT NOT NULL,         -- gloss, e.g. "HELLO"
  label_he           TEXT,
  label_en           TEXT,
  description        TEXT,
  locale             TEXT NOT NULL DEFAULT 'ISL',
  variants_json      TEXT NOT NULL DEFAULT '[]',
  grammar_json       TEXT NOT NULL DEFAULT '{}', -- only linguistically validated metadata
  validation_status  TEXT NOT NULL DEFAULT 'draft'
                     CHECK (validation_status IN ('draft', 'in_review', 'needs_expert', 'approved', 'rejected')),
  license_status     TEXT NOT NULL DEFAULT 'pending'
                     CHECK (license_status IN ('pending', 'needs_source', 'confirmed', 'rejected')),
  reviewer_ref       TEXT,
  reviewed_at        INTEGER,
  publication_status TEXT NOT NULL DEFAULT 'draft'
                     CHECK (publication_status IN ('draft', 'published', 'unpublished')),
  version            INTEGER NOT NULL DEFAULT 1,
  created_by         TEXT REFERENCES users (id) ON DELETE SET NULL,
  created_at         INTEGER NOT NULL,
  updated_at         INTEGER NOT NULL,
  -- Integrity rule: only expert-approved entries with a confirmed licence may be published.
  CHECK (publication_status <> 'published' OR (validation_status = 'approved' AND license_status = 'confirmed'))
);
CREATE INDEX idx_sign_entries_pub ON sign_entries (publication_status, validation_status);
CREATE INDEX idx_sign_entries_label ON sign_entries (canonical_label);

CREATE TABLE sign_entry_revisions (
  id            TEXT PRIMARY KEY,
  sign_entry_id TEXT NOT NULL REFERENCES sign_entries (id) ON DELETE CASCADE,
  version       INTEGER NOT NULL,
  snapshot_json TEXT NOT NULL,
  change_reason TEXT NOT NULL,
  changed_by    TEXT,
  created_at    INTEGER NOT NULL,
  UNIQUE (sign_entry_id, version)
);

CREATE TABLE dictionary_versions (
  id           TEXT PRIMARY KEY,
  version      INTEGER NOT NULL UNIQUE,
  notes        TEXT,
  entry_count  INTEGER NOT NULL,
  created_by   TEXT,
  published_at INTEGER NOT NULL
);

CREATE TABLE dictionary_version_entries (
  dictionary_version_id TEXT NOT NULL REFERENCES dictionary_versions (id) ON DELETE CASCADE,
  sign_entry_id         TEXT NOT NULL,
  sign_entry_version    INTEGER NOT NULL,
  PRIMARY KEY (dictionary_version_id, sign_entry_id)
);

CREATE TABLE animation_assets (
  id                   TEXT PRIMARY KEY,
  sign_entry_id        TEXT NOT NULL REFERENCES sign_entries (id) ON DELETE RESTRICT,
  r2_key               TEXT NOT NULL UNIQUE, -- opaque, server generated
  mime_type            TEXT NOT NULL,
  size_bytes           INTEGER,
  max_size_bytes       INTEGER NOT NULL,
  duration_ms          INTEGER,
  asset_version        INTEGER NOT NULL DEFAULT 1,
  license_json         TEXT NOT NULL,        -- licence id, holder, terms reference
  attribution_text     TEXT,
  approval_status      TEXT NOT NULL DEFAULT 'pending_upload'
                       CHECK (approval_status IN ('pending_upload', 'uploaded', 'approved', 'rejected', 'retired')),
  visibility           TEXT NOT NULL DEFAULT 'private' CHECK (visibility IN ('private', 'public')),
  checksum_sha256      TEXT,
  created_by           TEXT,
  created_at           INTEGER NOT NULL,
  updated_at           INTEGER NOT NULL,
  CHECK (visibility = 'private' OR approval_status = 'approved')
);
CREATE INDEX idx_animation_assets_entry ON animation_assets (sign_entry_id, approval_status);

CREATE TABLE animation_asset_revisions (
  id            TEXT PRIMARY KEY,
  asset_id      TEXT NOT NULL REFERENCES animation_assets (id) ON DELETE CASCADE,
  revision      INTEGER NOT NULL,
  snapshot_json TEXT NOT NULL,
  change_reason TEXT NOT NULL,
  changed_by    TEXT,
  created_at    INTEGER NOT NULL,
  UNIQUE (asset_id, revision)
);

CREATE TABLE asset_upload_grants (
  id         TEXT PRIMARY KEY,
  asset_id   TEXT NOT NULL REFERENCES animation_assets (id) ON DELETE CASCADE,
  token_hash TEXT NOT NULL UNIQUE,
  created_by TEXT,
  created_at INTEGER NOT NULL,
  expires_at INTEGER NOT NULL,
  used_at    INTEGER
);

-- ---------------------------------------------------------------------------
-- Platform administration & observability
-- ---------------------------------------------------------------------------
CREATE TABLE feature_flags (
  key         TEXT PRIMARY KEY,
  enabled     INTEGER NOT NULL DEFAULT 0,
  description TEXT,
  updated_by  TEXT,
  updated_at  INTEGER NOT NULL
);

CREATE TABLE audit_events (
  id              TEXT PRIMARY KEY,
  created_at      INTEGER NOT NULL,
  request_id      TEXT,
  actor_user_id   TEXT,
  actor_role      TEXT,
  action          TEXT NOT NULL,
  target_type     TEXT,
  target_id       TEXT,
  organization_id TEXT,
  outcome         TEXT NOT NULL CHECK (outcome IN ('success', 'denied', 'failure')),
  metadata_json   TEXT NOT NULL DEFAULT '{}'
);
CREATE INDEX idx_audit_events_created ON audit_events (created_at);
CREATE INDEX idx_audit_events_actor ON audit_events (actor_user_id, created_at);
CREATE INDEX idx_audit_events_action ON audit_events (action, created_at);

-- Hourly aggregate operational metrics (queue failures, provider latency…).
CREATE TABLE ops_metrics (
  bucket     TEXT NOT NULL, -- 'YYYY-MM-DDTHH' (UTC)
  name       TEXT NOT NULL,
  label      TEXT NOT NULL DEFAULT '',
  count      INTEGER NOT NULL DEFAULT 0,
  sum_value  INTEGER NOT NULL DEFAULT 0,
  max_value  INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (bucket, name, label)
);

-- Email delivery metadata; recipient is stored as a keyed hash only.
CREATE TABLE email_deliveries (
  id                   TEXT PRIMARY KEY,
  idempotency_key      TEXT NOT NULL UNIQUE,
  template             TEXT NOT NULL,
  locale               TEXT NOT NULL,
  recipient_hash       TEXT NOT NULL,
  provider             TEXT NOT NULL,
  status               TEXT NOT NULL CHECK (status IN ('pending', 'sent', 'failed', 'suppressed')),
  attempts             INTEGER NOT NULL DEFAULT 0,
  last_error_code      TEXT,
  provider_message_ref TEXT,
  created_at           INTEGER NOT NULL,
  updated_at           INTEGER NOT NULL
);

-- ---------------------------------------------------------------------------
-- OPT-IN saved translations (user-consented content).
-- Rows are written ONLY when (a) the user has enabled history (users.history_enabled = 1,
-- with recorded consent), (b) the plan grants history.available, and (c) the client
-- explicitly asks to save a specific translation. Nothing is saved automatically.
-- Rows are kept until the user deletes them or deletes the account.
-- ---------------------------------------------------------------------------
CREATE TABLE saved_translations (
  id               TEXT PRIMARY KEY,
  user_id          TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  kind             TEXT NOT NULL CHECK (kind IN ('emoji', 'sign')),
  source_text      TEXT NOT NULL,
  output_json      TEXT NOT NULL,
  language         TEXT NOT NULL,
  created_at       INTEGER NOT NULL
);
CREATE INDEX idx_saved_translations_user ON saved_translations (user_id, created_at);
