-- Starter concept inventory (from the Signa lexicon plan), grouped by category.
-- These are CANDIDATE CONCEPTS for coverage planning — NOT validated ISL translations.
-- No sign entry, sign form or animation is created here. Each concept must be linked to
-- a real ISL sign or structure, verified by ISL experts and Deaf community signers,
-- with a confirmed licence, before anything is published.
INSERT INTO lexical_concepts (concept_key, category, hebrew_terms_json, english_terms_json, status, created_at, updated_at) VALUES
  ('I', 'people_family', '["אני"]', '["I", "me"]', 'candidate', 0, 0),
  ('YOU', 'people_family', '["אתה", "את", "אתם"]', '["you"]', 'candidate', 0, 0),
  ('HE', 'people_family', '["הוא"]', '["he"]', 'candidate', 0, 0),
  ('SHE', 'people_family', '["היא"]', '["she"]', 'candidate', 0, 0),
  ('WE', 'people_family', '["אנחנו"]', '["we"]', 'candidate', 0, 0),
  ('PERSON', 'people_family', '["אדם", "בן אדם"]', '["person"]', 'candidate', 0, 0),
  ('BOY', 'people_family', '["ילד"]', '["boy", "child"]', 'candidate', 0, 0),
  ('GIRL', 'people_family', '["ילדה"]', '["girl"]', 'candidate', 0, 0),
  ('PARENT', 'people_family', '["הורה", "הורים"]', '["parent"]', 'candidate', 0, 0),
  ('MOTHER', 'people_family', '["אמא", "אימא"]', '["mother"]', 'candidate', 0, 0),
  ('FATHER', 'people_family', '["אבא"]', '["father"]', 'candidate', 0, 0),
  ('BROTHER', 'people_family', '["אח"]', '["brother"]', 'candidate', 0, 0),
  ('SISTER', 'people_family', '["אחות"]', '["sister"]', 'candidate', 0, 0),
  ('FRIEND', 'people_family', '["חבר", "חברה"]', '["friend"]', 'candidate', 0, 0),
  ('FAMILY', 'people_family', '["משפחה"]', '["family"]', 'candidate', 0, 0),
  ('HELLO', 'greetings', '["שלום", "היי"]', '["hello"]', 'candidate', 0, 0),
  ('GOODBYE', 'greetings', '["להתראות", "ביי"]', '["goodbye"]', 'candidate', 0, 0),
  ('GOOD_MORNING', 'greetings', '["בוקר טוב"]', '["good morning"]', 'candidate', 0, 0),
  ('GOOD_EVENING', 'greetings', '["ערב טוב"]', '["good evening"]', 'candidate', 0, 0),
  ('THANK_YOU', 'greetings', '["תודה", "תודה רבה"]', '["thank you"]', 'candidate', 0, 0),
  ('PLEASE', 'greetings', '["בבקשה"]', '["please"]', 'candidate', 0, 0),
  ('SORRY', 'greetings', '["סליחה"]', '["sorry", "excuse me"]', 'candidate', 0, 0),
  ('WELCOME', 'greetings', '["ברוך הבא", "ברוכה הבאה", "ברוכים הבאים"]', '["welcome"]', 'candidate', 0, 0),
  ('CONGRATULATIONS', 'greetings', '["מזל טוב"]', '["congratulations"]', 'candidate', 0, 0),
  ('WANT', 'actions', '["רוצה"]', '["want"]', 'candidate', 0, 0),
  ('NEED', 'actions', '["צריך", "צריכה"]', '["need"]', 'candidate', 0, 0),
  ('CAN', 'actions', '["יכול", "יכולה"]', '["can"]', 'candidate', 0, 0),
  ('KNOW', 'actions', '["יודע", "יודעת"]', '["know"]', 'candidate', 0, 0),
  ('UNDERSTAND', 'actions', '["מבין", "מבינה"]', '["understand"]', 'candidate', 0, 0),
  ('GO', 'actions', '["הולך", "הולכת"]', '["go"]', 'candidate', 0, 0),
  ('ARRIVE', 'actions', '["מגיע", "מגיעה"]', '["arrive", "come"]', 'candidate', 0, 0),
  ('GIVE', 'actions', '["נותן", "נותנת"]', '["give"]', 'candidate', 0, 0),
  ('TAKE', 'actions', '["לוקח", "לוקחת"]', '["take"]', 'candidate', 0, 0),
  ('EAT', 'actions', '["אוכל", "אוכלת"]', '["eat"]', 'candidate', 0, 0),
  ('DRINK', 'actions', '["שותה"]', '["drink"]', 'candidate', 0, 0),
  ('WORK', 'actions', '["עובד", "עובדת", "עבודה"]', '["work"]', 'candidate', 0, 0),
  ('LEARN', 'actions', '["לומד", "לומדת"]', '["learn", "study"]', 'candidate', 0, 0),
  ('WAIT', 'actions', '["מחכה"]', '["wait"]', 'candidate', 0, 0),
  ('WHO', 'questions', '["מי"]', '["who"]', 'candidate', 0, 0),
  ('WHAT', 'questions', '["מה"]', '["what"]', 'candidate', 0, 0),
  ('WHERE', 'questions', '["איפה"]', '["where"]', 'candidate', 0, 0),
  ('WHEN', 'questions', '["מתי"]', '["when"]', 'candidate', 0, 0),
  ('WHY', 'questions', '["למה"]', '["why"]', 'candidate', 0, 0),
  ('HOW', 'questions', '["איך"]', '["how"]', 'candidate', 0, 0),
  ('HOW_MANY', 'questions', '["כמה"]', '["how many", "how much"]', 'candidate', 0, 0),
  ('WHICH', 'questions', '["איזה", "איזו"]', '["which"]', 'candidate', 0, 0),
  ('WHOSE', 'questions', '["של מי"]', '["whose"]', 'candidate', 0, 0),
  ('HAPPY', 'feelings', '["שמח", "שמחה"]', '["happy"]', 'candidate', 0, 0),
  ('SAD', 'feelings', '["עצוב", "עצובה"]', '["sad"]', 'candidate', 0, 0),
  ('ANGRY', 'feelings', '["כועס", "כועסת"]', '["angry"]', 'candidate', 0, 0),
  ('AFRAID', 'feelings', '["מפחד", "מפחדת"]', '["afraid"]', 'candidate', 0, 0),
  ('EXCITED', 'feelings', '["מתרגש", "מתרגשת"]', '["excited"]', 'candidate', 0, 0),
  ('TIRED', 'feelings', '["עייף", "עייפה"]', '["tired"]', 'candidate', 0, 0),
  ('HUNGRY', 'feelings', '["רעב", "רעבה"]', '["hungry"]', 'candidate', 0, 0),
  ('THIRSTY', 'feelings', '["צמא", "צמאה"]', '["thirsty"]', 'candidate', 0, 0),
  ('WORRIED', 'feelings', '["מודאג", "מודאגת"]', '["worried"]', 'candidate', 0, 0),
  ('CALM', 'feelings', '["רגוע", "רגועה"]', '["calm"]', 'candidate', 0, 0),
  ('TODAY', 'time', '["היום"]', '["today"]', 'candidate', 0, 0),
  ('YESTERDAY', 'time', '["אתמול"]', '["yesterday"]', 'candidate', 0, 0),
  ('TOMORROW', 'time', '["מחר"]', '["tomorrow"]', 'candidate', 0, 0),
  ('NOW', 'time', '["עכשיו"]', '["now"]', 'candidate', 0, 0),
  ('LATER', 'time', '["אחר כך"]', '["later"]', 'candidate', 0, 0),
  ('BEFORE', 'time', '["קודם"]', '["before", "earlier"]', 'candidate', 0, 0),
  ('MORNING', 'time', '["בוקר"]', '["morning"]', 'candidate', 0, 0),
  ('NOON', 'time', '["צהריים"]', '["noon", "afternoon"]', 'candidate', 0, 0),
  ('EVENING', 'time', '["ערב"]', '["evening"]', 'candidate', 0, 0),
  ('NIGHT', 'time', '["לילה"]', '["night"]', 'candidate', 0, 0),
  ('WEEK', 'time', '["שבוע"]', '["week"]', 'candidate', 0, 0),
  ('MONTH', 'time', '["חודש"]', '["month"]', 'candidate', 0, 0),
  ('YEAR', 'time', '["שנה"]', '["year"]', 'candidate', 0, 0),
  ('HOME', 'places_transport', '["בית"]', '["home", "house"]', 'candidate', 0, 0),
  ('SCHOOL', 'places_transport', '["בית ספר"]', '["school"]', 'candidate', 0, 0),
  ('HOSPITAL', 'places_transport', '["בית חולים"]', '["hospital"]', 'candidate', 0, 0),
  ('SHOP', 'places_transport', '["חנות"]', '["shop", "store"]', 'candidate', 0, 0),
  ('STREET', 'places_transport', '["רחוב"]', '["street"]', 'candidate', 0, 0),
  ('CITY', 'places_transport', '["עיר"]', '["city"]', 'candidate', 0, 0),
  ('BUS', 'places_transport', '["אוטובוס"]', '["bus"]', 'candidate', 0, 0),
  ('TRAIN', 'places_transport', '["רכבת"]', '["train"]', 'candidate', 0, 0),
  ('STATION', 'places_transport', '["תחנה"]', '["station", "stop"]', 'candidate', 0, 0),
  ('TAXI', 'places_transport', '["מונית"]', '["taxi"]', 'candidate', 0, 0),
  ('CAR', 'places_transport', '["רכב", "מכונית"]', '["car"]', 'candidate', 0, 0),
  ('HELP', 'health_help', '["עזרה"]', '["help"]', 'candidate', 0, 0),
  ('DOCTOR', 'health_help', '["רופא", "רופאה"]', '["doctor"]', 'candidate', 0, 0),
  ('PAIN', 'health_help', '["כאב"]', '["pain"]', 'candidate', 0, 0),
  ('SICK', 'health_help', '["חולה"]', '["sick"]', 'candidate', 0, 0),
  ('MEDICINE', 'health_help', '["תרופה"]', '["medicine"]', 'candidate', 0, 0),
  ('INJURY', 'health_help', '["פציעה"]', '["injury"]', 'candidate', 0, 0),
  ('EMERGENCY', 'health_help', '["חירום"]', '["emergency"]', 'candidate', 0, 0),
  ('POLICE', 'health_help', '["משטרה"]', '["police"]', 'candidate', 0, 0),
  ('AMBULANCE', 'health_help', '["אמבולנס"]', '["ambulance"]', 'candidate', 0, 0),
  ('MONEY', 'service_money', '["כסף"]', '["money"]', 'candidate', 0, 0),
  ('PRICE', 'service_money', '["מחיר"]', '["price"]', 'candidate', 0, 0),
  ('BUY', 'service_money', '["לקנות", "קונה"]', '["buy"]', 'candidate', 0, 0),
  ('SELL', 'service_money', '["למכור", "מוכר"]', '["sell"]', 'candidate', 0, 0),
  ('PAY', 'service_money', '["לשלם", "משלם"]', '["pay"]', 'candidate', 0, 0),
  ('BILL', 'service_money', '["חשבון"]', '["bill", "account"]', 'candidate', 0, 0),
  ('CARD', 'service_money', '["כרטיס"]', '["card", "ticket"]', 'candidate', 0, 0),
  ('BANK', 'service_money', '["בנק"]', '["bank"]', 'candidate', 0, 0),
  ('SERVICE', 'service_money', '["שירות"]', '["service"]', 'candidate', 0, 0),
  ('ORDER', 'service_money', '["הזמנה"]', '["order", "reservation"]', 'candidate', 0, 0),
  ('BIG', 'descriptions_quantities', '["גדול", "גדולה"]', '["big"]', 'candidate', 0, 0),
  ('SMALL', 'descriptions_quantities', '["קטן", "קטנה"]', '["small"]', 'candidate', 0, 0),
  ('LONG', 'descriptions_quantities', '["ארוך", "ארוכה"]', '["long"]', 'candidate', 0, 0),
  ('SHORT', 'descriptions_quantities', '["קצר", "קצרה"]', '["short"]', 'candidate', 0, 0),
  ('GOOD', 'descriptions_quantities', '["טוב", "טובה"]', '["good"]', 'candidate', 0, 0),
  ('BAD', 'descriptions_quantities', '["רע", "רעה"]', '["bad"]', 'candidate', 0, 0),
  ('NEW', 'descriptions_quantities', '["חדש", "חדשה"]', '["new"]', 'candidate', 0, 0),
  ('OLD', 'descriptions_quantities', '["ישן", "ישנה"]', '["old (thing)"]', 'candidate', 0, 0),
  ('MANY', 'descriptions_quantities', '["הרבה"]', '["many", "a lot"]', 'candidate', 0, 0),
  ('FEW', 'descriptions_quantities', '["מעט"]', '["few", "a little"]', 'candidate', 0, 0),
  ('MORE', 'descriptions_quantities', '["יותר"]', '["more"]', 'candidate', 0, 0),
  ('LESS', 'descriptions_quantities', '["פחות"]', '["less"]', 'candidate', 0, 0),
  ('FIRST', 'descriptions_quantities', '["ראשון", "ראשונה"]', '["first"]', 'candidate', 0, 0),
  ('LAST', 'descriptions_quantities', '["אחרון", "אחרונה"]', '["last"]', 'candidate', 0, 0);
